name: Continous Integration

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.11
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

  test:
    needs:
      - build
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:8.0.39
        ports:
          - 3306:3306
        options: >
          --health-cmd="mysqladmin ping --silent"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3
        env:
          MYSQL_ROOT_PASSWORD: password
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Create .env file
        run: |
          echo "DB_USER=root" > .env
          echo "DB_PASSWORD=password" >> .env
          echo "DB_DATABASE=addresses" >> .env
          echo "DB_HOST=127.0.0.1" >> .env
          echo "DB_PORT=3306" >> .env

      - name: Wait for MySQL to be ready
        run: |
          until mysqladmin ping -h"127.0.0.1" --silent; do
            echo "Waiting for MySQL..."
            sleep 5
          done

      - name: Run SQL Script
        run: |
          mysql -h 127.0.0.1 -u root -p"password" < addresses.sql

      - name: Run pytests
        run: |
          pytest

      - name: Remove .env file
        run: |
          rm -f .env