name: Continous Integration

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      
      name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.11

      name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
  test:
    needs: 
      - build:
    runs-on: ubuntu-latest
    steps:
      name: Run tests
      run: |
        pytest